name: codock
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  argon2: ^1.0.1
  build_runner: ^2.4.12
  dart_frog: ^1.1.0
  dart_frog_cors: ^2.0.0
  dotenv: ^4.2.0
  flutter_cors: ^1.5.0
  json_annotation: ^4.9.0
  orm: ^3.4.8

dev_dependencies:
  json_serializable: ^6.0.0
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
